import type { Drone } from "@/lib/types";

export const drones: Drone[] = [
  {
    id: "dr-01",
    droneCode: "DRN-001",
    model: "Falcon X2",
    maxPayloadKg: 85,
    cargoBayLengthCm: 60,
    cargoBayWidthCm: 45,
    cargoBayHeightCm: 40,
    maxRangeKm: 28,
    batteryCapacityPct: 92,
    speedKmh: 65,
    status: "available",
    homeWarehouseId: "wh-01",
    currentLat: 30.2672,
    currentLng: -97.7431,
  },
  {
    id: "dr-02",
    droneCode: "DRN-002",
    model: "Falcon X2",
    maxPayloadKg: 85,
    cargoBayLengthCm: 60,
    cargoBayWidthCm: 45,
    cargoBayHeightCm: 40,
    maxRangeKm: 28,
    batteryCapacityPct: 41,
    speedKmh: 65,
    status: "in_flight",
    homeWarehouseId: "wh-01",
    currentLat: 30.2551,
    currentLng: -97.7288,
  },
  {
    id: "dr-03",
    droneCode: "DRN-003",
    model: "Sparrow Lite",
    maxPayloadKg: 40,
    cargoBayLengthCm: 40,
    cargoBayWidthCm: 30,
    cargoBayHeightCm: 25,
    maxRangeKm: 18,
    batteryCapacityPct: 100,
    speedKmh: 55,
    status: "charging",
    homeWarehouseId: "wh-02",
    currentLat: 30.2849,
    currentLng: -97.7341,
  },
  {
    id: "dr-04",
    droneCode: "DRN-004",
    model: "Falcon X2",
    maxPayloadKg: 85,
    cargoBayLengthCm: 60,
    cargoBayWidthCm: 45,
    cargoBayHeightCm: 40,
    maxRangeKm: 28,
    batteryCapacityPct: 76,
    speedKmh: 65,
    status: "available",
    homeWarehouseId: "wh-02",
    currentLat: 30.2849,
    currentLng: -97.7341,
  },
  {
    id: "dr-05",
    droneCode: "DRN-005",
    model: "Condor Heavy",
    maxPayloadKg: 85,
    cargoBayLengthCm: 70,
    cargoBayWidthCm: 50,
    cargoBayHeightCm: 45,
    maxRangeKm: 35,
    batteryCapacityPct: 15,
    speedKmh: 58,
    status: "maintenance",
    homeWarehouseId: "wh-05",
    currentLat: 30.3005,
    currentLng: -97.8147,
  },
  {
    id: "dr-06",
    droneCode: "DRN-006",
    model: "Sparrow Lite",
    maxPayloadKg: 40,
    cargoBayLengthCm: 40,
    cargoBayWidthCm: 30,
    cargoBayHeightCm: 25,
    maxRangeKm: 18,
    batteryCapacityPct: 88,
    speedKmh: 55,
    status: "available",
    homeWarehouseId: "wh-03",
    currentLat: 30.2495,
    currentLng: -97.7089,
  },
  {
    id: "dr-07",
    droneCode: "DRN-007",
    model: "Falcon X2",
    maxPayloadKg: 85,
    cargoBayLengthCm: 60,
    cargoBayWidthCm: 45,
    cargoBayHeightCm: 40,
    maxRangeKm: 28,
    batteryCapacityPct: 63,
    speedKmh: 65,
    status: "in_flight",
    homeWarehouseId: "wh-05",
    currentLat: 30.2733,
    currentLng: -97.7802,
  },
  {
    id: "dr-08",
    droneCode: "DRN-008",
    model: "Condor Heavy",
    maxPayloadKg: 85,
    cargoBayLengthCm: 70,
    cargoBayWidthCm: 50,
    cargoBayHeightCm: 45,
    maxRangeKm: 35,
    batteryCapacityPct: 100,
    speedKmh: 58,
    status: "charging",
    homeWarehouseId: "wh-01",
    currentLat: 30.2672,
    currentLng: -97.7431,
  },
  {
    id: "dr-09",
    droneCode: "DRN-009",
    model: "Sparrow Lite",
    maxPayloadKg: 40,
    cargoBayLengthCm: 40,
    cargoBayWidthCm: 30,
    cargoBayHeightCm: 25,
    maxRangeKm: 18,
    batteryCapacityPct: 54,
    speedKmh: 55,
    status: "available",
    homeWarehouseId: "wh-05",
    currentLat: 30.3005,
    currentLng: -97.8147,
  },
  {
    id: "dr-10",
    droneCode: "DRN-010",
    model: "Falcon X2",
    maxPayloadKg: 85,
    cargoBayLengthCm: 60,
    cargoBayWidthCm: 45,
    cargoBayHeightCm: 40,
    maxRangeKm: 28,
    batteryCapacityPct: 8,
    speedKmh: 65,
    status: "maintenance",
    homeWarehouseId: "wh-02",
    currentLat: 30.2849,
    currentLng: -97.7341,
  },
];
