import type { Product } from "@/lib/types";

function volume(l: number, w: number, h: number) {
  return l * w * h;
}

export const products: Product[] = [
  {
    id: "pd-001",
    sellerId: "sl-01",
    warehouseId: "wh-01",
    name: "Ceramic Table Lamp",
    description: "Hand-glazed ceramic base with a linen drum shade.",
    category: "Home Decor",
    price: 48.99,
    stockQty: 120,
    weightKg: 2.4,
    lengthCm: 25,
    widthCm: 25,
    heightCm: 45,
    volumeCm3: volume(25, 25, 45),
    fragile: true,
    images: [],
    status: "active",
    createdAt: "2026-02-06T10:00:00Z",
  },
  {
    id: "pd-002",
    sellerId: "sl-01",
    warehouseId: "wh-02",
    name: "Woven Storage Basket Set",
    description: "Set of 3 seagrass storage baskets, nesting sizes.",
    category: "Home Decor",
    price: 34.5,
    stockQty: 80,
    weightKg: 3.1,
    lengthCm: 40,
    widthCm: 40,
    heightCm: 35,
    volumeCm3: volume(40, 40, 35),
    fragile: false,
    images: [],
    status: "active",
    createdAt: "2026-02-07T09:30:00Z",
  },
  {
    id: "pd-003",
    sellerId: "sl-02",
    warehouseId: "wh-01",
    name: "Smart WiFi Plug (2-Pack)",
    description: "App-controlled smart plugs with energy monitoring.",
    category: "Electronics",
    price: 19.99,
    stockQty: 300,
    weightKg: 0.3,
    lengthCm: 10,
    widthCm: 8,
    heightCm: 6,
    volumeCm3: volume(10, 8, 6),
    fragile: false,
    images: [],
    status: "active",
    createdAt: "2026-01-21T08:00:00Z",
  },
  {
    id: "pd-004",
    sellerId: "sl-02",
    warehouseId: "wh-01",
    name: "4K Streaming Media Player",
    description: "Compact streaming box with voice remote.",
    category: "Electronics",
    price: 59.99,
    stockQty: 150,
    weightKg: 0.5,
    lengthCm: 12,
    widthCm: 12,
    heightCm: 3,
    volumeCm3: volume(12, 12, 3),
    fragile: true,
    images: [],
    status: "active",
    createdAt: "2026-01-22T08:30:00Z",
  },
  {
    id: "pd-005",
    sellerId: "sl-03",
    warehouseId: "wh-02",
    name: "Backpacking Tent (2-Person)",
    description: "Ultralight freestanding tent, 2.1kg trail weight.",
    category: "Outdoor",
    price: 129.0,
    stockQty: 45,
    weightKg: 2.8,
    lengthCm: 55,
    widthCm: 20,
    heightCm: 20,
    volumeCm3: volume(55, 20, 20),
    fragile: false,
    images: [],
    status: "active",
    createdAt: "2026-01-25T11:00:00Z",
  },
  {
    id: "pd-006",
    sellerId: "sl-03",
    warehouseId: "wh-05",
    name: "Insulated Camping Cooler 45L",
    description: "Rotomolded cooler, keeps ice for up to 5 days.",
    category: "Outdoor",
    price: 89.0,
    stockQty: 30,
    weightKg: 6.2,
    lengthCm: 70,
    widthCm: 40,
    heightCm: 40,
    volumeCm3: volume(70, 40, 40),
    fragile: false,
    images: [],
    status: "active",
    createdAt: "2026-01-26T11:30:00Z",
  },
  {
    id: "pd-007",
    sellerId: "sl-04",
    warehouseId: "wh-03",
    name: "Letterpress Notebook Set",
    description: "Set of 3 A5 notebooks, letterpress-printed covers.",
    category: "Stationery",
    price: 22.0,
    stockQty: 200,
    weightKg: 0.6,
    lengthCm: 21,
    widthCm: 15,
    heightCm: 5,
    volumeCm3: volume(21, 15, 5),
    fragile: false,
    images: [],
    status: "active",
    createdAt: "2026-02-12T09:00:00Z",
  },
  {
    id: "pd-008",
    sellerId: "sl-04",
    warehouseId: "wh-03",
    name: "Ceramic Desk Organizer",
    description: "Three-compartment glazed ceramic desk tray.",
    category: "Stationery",
    price: 27.5,
    stockQty: 60,
    weightKg: 1.4,
    lengthCm: 20,
    widthCm: 15,
    heightCm: 10,
    volumeCm3: volume(20, 15, 10),
    fragile: true,
    images: [],
    status: "active",
    createdAt: "2026-02-13T09:15:00Z",
  },
  {
    id: "pd-009",
    sellerId: "sl-05",
    warehouseId: "wh-05",
    name: "Self-Watering Planter (Large)",
    description: "24-inch self-watering planter with reservoir.",
    category: "Garden",
    price: 42.0,
    stockQty: 90,
    weightKg: 3.8,
    lengthCm: 35,
    widthCm: 35,
    heightCm: 40,
    volumeCm3: volume(35, 35, 40),
    fragile: true,
    images: [],
    status: "active",
    createdAt: "2026-01-07T10:00:00Z",
  },
  {
    id: "pd-010",
    sellerId: "sl-05",
    warehouseId: "wh-05",
    name: "Indoor Herb Garden Kit",
    description: "Countertop hydroponic kit with grow light.",
    category: "Garden",
    price: 55.0,
    stockQty: 70,
    weightKg: 2.1,
    lengthCm: 30,
    widthCm: 20,
    heightCm: 25,
    volumeCm3: volume(30, 20, 25),
    fragile: false,
    images: [],
    status: "active",
    createdAt: "2026-01-08T10:30:00Z",
  },
  {
    id: "pd-011",
    sellerId: "sl-06",
    warehouseId: "wh-01",
    name: "Adjustable Dumbbell Set (84.5kg pair)",
    description: "Quick-adjust dumbbell pair, 2.5kg to 42.25kg each.",
    category: "Fitness",
    price: 349.0,
    stockQty: 12,
    weightKg: 84.5,
    lengthCm: 90,
    widthCm: 25,
    heightCm: 25,
    volumeCm3: volume(90, 25, 25),
    fragile: false,
    images: [],
    status: "active",
    createdAt: "2026-02-17T10:00:00Z",
  },
  {
    id: "pd-012",
    sellerId: "sl-06",
    warehouseId: "wh-05",
    name: "Olympic Barbell + Plate Set (90kg)",
    description: "7ft Olympic barbell with full plate set.",
    category: "Fitness",
    price: 289.0,
    stockQty: 8,
    weightKg: 90,
    lengthCm: 220,
    widthCm: 30,
    heightCm: 30,
    volumeCm3: volume(220, 30, 30),
    fragile: false,
    images: [],
    status: "draft",
    createdAt: "2026-02-18T10:30:00Z",
  },
  {
    id: "pd-013",
    sellerId: "sl-07",
    warehouseId: "wh-02",
    name: "Single-Origin Coffee Beans (1kg)",
    description: "Light-roast Ethiopian Yirgacheffe, whole bean.",
    category: "Food & Beverage",
    price: 24.0,
    stockQty: 250,
    weightKg: 1.0,
    lengthCm: 20,
    widthCm: 12,
    heightCm: 8,
    volumeCm3: volume(20, 12, 8),
    fragile: false,
    images: [],
    status: "active",
    createdAt: "2026-01-31T08:00:00Z",
  },
  {
    id: "pd-014",
    sellerId: "sl-07",
    warehouseId: "wh-02",
    name: "Pour-Over Coffee Maker",
    description: "Borosilicate glass pour-over with reusable filter.",
    category: "Food & Beverage",
    price: 38.0,
    stockQty: 0,
    weightKg: 1.2,
    lengthCm: 25,
    widthCm: 15,
    heightCm: 15,
    volumeCm3: volume(25, 15, 15),
    fragile: true,
    images: [],
    status: "out_of_stock",
    createdAt: "2026-02-01T08:30:00Z",
  },
  {
    id: "pd-015",
    sellerId: "sl-10",
    warehouseId: "wh-03",
    name: "Glow-in-Dark Party Favors (50pc)",
    description: "Assorted glow bracelets and novelty toys.",
    category: "Novelty",
    price: 15.99,
    stockQty: 500,
    weightKg: 0.8,
    lengthCm: 30,
    widthCm: 20,
    heightCm: 10,
    volumeCm3: volume(30, 20, 10),
    fragile: false,
    images: [],
    status: "suspended",
    createdAt: "2025-11-10T10:00:00Z",
  },
];
