import type { Warehouse } from "@/lib/types";

export const warehouses: Warehouse[] = [
  {
    id: "wh-01",
    name: "Northgate Distribution Center",
    sellerFacing: true,
    city: "Austin, TX",
    latitude: 30.2672,
    longitude: -97.7431,
    capacity: 12000,
    droneDockCount: 8,
    chargingStation: true,
  },
  {
    id: "wh-02",
    name: "Riverside Fulfillment Hub",
    sellerFacing: true,
    city: "Austin, TX",
    latitude: 30.2849,
    longitude: -97.7341,
    capacity: 9000,
    droneDockCount: 6,
    chargingStation: true,
  },
  {
    id: "wh-03",
    name: "Eastside Micro-Warehouse",
    sellerFacing: true,
    city: "Austin, TX",
    latitude: 30.2495,
    longitude: -97.7089,
    capacity: 4000,
    droneDockCount: 3,
    chargingStation: false,
  },
  {
    id: "wh-04",
    name: "Southpark Relay Station",
    sellerFacing: false,
    city: "Austin, TX",
    latitude: 30.2129,
    longitude: -97.7688,
    capacity: 1500,
    droneDockCount: 4,
    chargingStation: true,
  },
  {
    id: "wh-05",
    name: "Westlake Fulfillment Center",
    sellerFacing: true,
    city: "Austin, TX",
    latitude: 30.3005,
    longitude: -97.8147,
    capacity: 7000,
    droneDockCount: 5,
    chargingStation: false,
  },
  {
    id: "wh-06",
    name: "Domain Charging Outpost",
    sellerFacing: false,
    city: "Austin, TX",
    latitude: 30.3966,
    longitude: -97.7247,
    capacity: 800,
    droneDockCount: 6,
    chargingStation: true,
  },
];
